### ISSUE TITLE
ModuleNotFoundError: No module named 'async_timeout'

### ISSUE THREAD

**Issue by xtipacko** [stellarbit/aioping#1]
I have this issue:
How to resolve it?
Перевод на русский:
Ай хэв виз ишью, хау ту резолв ит?

`ModuleNotFoundError: No module named 'async_timeout'`

UPD
Блин ну я и тупой :)

```
#pip install async-timeout
pip install aiodns
```

Resolved :)

**Comment by anton-belousov** [comment]
You're welcome! :)
