### ISSUE TITLE
The following changes will allow this to work with python 3.8 on windows.

### ISSUE THREAD

**Issue by hanieljgoertz** [stellarbit/aioping#14]
time.clock is deprecated.  The windows even loop policy has changed.  in __init__.py do:

default_timer = time.time

if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

This fixes these issues.

**Comment by anton-belousov** [comment]
Thanks! Will add to 0.3.0
