### ISSUE TITLE
Root-less ping

### ISSUE THREAD

**Issue by Yamakaky** [stellarbit/aioping#23]
`ping` is able to run without root on modern linux. See https://unix.stackexchange.com/questions/617927/why-ping-works-without-capability-and-setuid/617936#617936. Maybe it can be be adapted here? I tried to modify the `socket()` call but I get a timeout every time, maybe I missed something.

**Comment by te0d** [comment]
Changing the socket type from `SOCK_RAW` to `SOCK_DGRAM` looks like it may allow it to work as a non-root user? It has worked for my purposes, but I have not tested it extensively.

**Comment by mattmart3** [comment]
[Here](https://github.com/kyan001/ping3/blob/v4.0.0/ping3/__init__.py#L285) ping3 fallbacks to SOCK_DGRAM on permission errors and it seems to be working fine.

Edit: see [ping3 commit that adds root-less ping support](https://github.com/kyan001/ping3/commit/0a6fdbaa24482417c2f9773f28b73e90c6af2c07)

**Comment by Yamakaky** [comment]
Nice!
