### ISSUE TITLE
Can't ping IPv6 addresses

### ISSUE THREAD

**Issue by vzoranb** [stellarbit/aioping#29]
Hi, I am not sure if this is the right place to post a question but I was not able to find an answer on the internet. 
When pinging any IPv6 address I keep getting timeouts. 
Here is the code:
`import asyncio
import aioping

async def ping(ip):
    try:
        rtt = await aioping.ping(ip, timeout=5)
        return f"{ip} - {rtt} ms"
    except TimeoutError:
        return f"{ip} - timeout"

async def main():
    ipv6_list = ['2001:4860:4860::8888', '8.8.8.8']
    tasks = []
    for ip in ipv6_list:
        tasks.append(asyncio.create_task(ping(ip)))
        await asyncio.sleep(0.01) # 10 ms delay between pings
    results = await asyncio.gather(*tasks)
    print(results)

asyncio.run(main())
`
Here is the result:
testscripts $ sudo python3 ./ping.py
['2001:4860:4860::8888 - timeout', '8.8.8.8 - 0.018215064017567784 ms']

testscripts $ ping  2001:4860:4860::8888
PING 2001:4860:4860::8888(2001:4860:4860::8888) 56 data bytes
64 bytes from 2001:4860:4860::8888: icmp_seq=1 ttl=117 time=7.26 ms

I would appreciate your help.
Best!

**Comment by anton-belousov** [comment]
Should be fixed in master
