### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by asantoni** [stellarbit/aioping#5]
aioping does not work correctly on Windows 10 because this code around line 230 of `__init__.py` blows up:
```
    loop = asyncio.get_event_loop()
    info = await loop.getaddrinfo(dest_addr, 0)
    family = info[2][0]
    addr = info[2][4]
````
You get an exception because `info` is only of length 1 on Windows.

This code looks sketchy to me (why choose the third `info` element?), so I hacked it to just pick a random element and I'll send a PR shortly. My understand is that this is doing a DNS lookup, and if there's multiple records returned, we should picking a random one. The code should probably be extended to handle IPv6 more explicitly too, but I'll leave that as an exercise for someone else!

**Comment by anton-belousov** [comment]
@asantoni thanks for the noticing that and for the PR, I hope will have time to review it and update the library by the end of the week (have a huge workload currently)

**Comment by bradh11** [comment]
is this still an issue?

**Comment by asantoni** [comment]
Yes, looks like only one new (unrelated) commit in master since I opened this.

If you need it working on Windows right now, feel free to use my fork temporarily. (asantoni/aioping)

**Comment by anton-belousov** [comment]
Sorry for delay guys, just merged the request, will update the distro now. @asantoni thanks a lot for the fix!

**Comment by bradh11** [comment]
confirmed working/fixed.  Thanks for the merge!  great library btw.
